---
name: Deploy Docs

on:
  workflow_dispatch:

env:
  NODE_VERSION: 18

jobs:
  deploy:
    name: Deploy Docs
    runs-on: ubuntu-latest
    steps:
      - name: Check out a copy of the repo
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # - name: Set Version Path
      #   run: echo "ADDON_DOCS_VERSION_PATH=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Set Latest
        run: echo "ADDON_DOCS_UPDATE_LATEST=true" >> $GITHUB_ENV

      - name: Print Env
        run: echo $GITHUB_ENV

      - name: Build docs
        run: pnpm run build
        working-directory: 'docs'

      - name: Deploy
        env:
          DEPLOY_KEY: ${{ secrets.GH_PA_TOKEN }}
        run: pnpm exec ember deploy production --verbose --activate
        working-directory: 'docs'
