---
name: Deploy Docs

on:
  workflow_dispatch:

jobs:
  deploy_docs:
    name: Deploy Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: ./.github/actions/pnpm
      - uses: ./.github/actions/assert-build
      - uses: ./.github/actions/download-built-package
      - run: echo "ADDON_DOCS_VERSION_PATH=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - run: echo "ADDON_DOCS_UPDATE_LATEST=true" >> $GITHUB_ENV
      - name: Deploy
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: pnpm ember deploy production --verbose --activate
